version: "3.9"

services:
  backend:
    container_name: chat-application-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Local port 3001 → Container port 3000
    env_file:
      - ./Backend/.env
    restart: always
    command: npm start
    networks:
      - chat-application-network

  frontend:
    container_name: chat-application-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"  # Local port 5174 → Container port 5173
    depends_on:
      - backend
    restart: always
    command: serve -s dist -l 5173
    networks:
      - chat-application-network

networks:
  chat-application-network:
    driver: bridge
