name: Docker CD

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest  # Make sure your runner is properly tagged and available

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "Starting deployment of Chat Application..."

            # Pull latest Docker images from Docker Hub
            docker pull nitheesh2005/chat-application-backend:latest
            docker pull nitheesh2005/chat-application-frontend:latest

            # Stop and remove old containers (ignore errors if not running)
            docker stop chat-application-backend || echo "chat-application-backend container not running"
            docker rm chat-application-backend || echo "chat-application-backend container not found"

            docker stop chat-application-frontend || echo "chat-application-frontend container not running"
            docker rm chat-application-frontend || echo "chat-application-frontend container not found"

            # Run new containers with port mappings and restart policy
            docker run -d --name chat-application-backend -p 3001:3000 --restart unless-stopped nitheesh2005/chat-application-backend:latest

            docker run -d --name chat-application-frontend -p 5174:5173 --restart unless-stopped nitheesh2005/chat-application-frontend:latest

            echo "Deployment completed successfully."
